### ISSUE TITLE
Support for Top five extension

### ISSUE THREAD

**Issue by Galixte** [VSEphpbb/topicpreview#26]
Hi,

on the index page, i have only the first topic listed in top five which is previewed correctly, the next topics have the same preview than the first topic listed in top five.

**Comment by VSEphpbb** [comment]
Thanks for pointing that out but that's for that extension's author to fix. 
https://github.com/RMcGirr83/phpBB-3.1-topfive/pull/9

In the mean time, you should be using the current validated release, not his unvalidated development version.
