### ISSUE TITLE
No preview available (More Details)

### ISSUE THREAD

**Issue by FilocJD** [VSEphpbb/topicpreview#27]
Currently running phpbb 3.1.6 with the following below.

SiteSplat - Flatboots theme (latest) 
BBOOTS - BBCore extension (latest)

Topic Preview will not display with all extensions disabled, and different theme. Used v2.2.2 which did not work. Running 2.2.3-dev with no positive results.

**Comment by VSEphpbb** [comment]
Flatboots themes do not support other extensions than their own paid versions.
